### ISSUE TITLE
Isn't this patented?

### ISSUE THREAD

**Issue by hyankov** [mrvancil/simhash-csharp#1]
I may want to use this, but isn't the algorithm patented by Google?

http://www.patents.com/us-7158961.html

**Comment by mrvancil** [comment]
Hey!  Great question!  I played around with this algorithm (3 years ago) to test out a couple of duplicate detection approaches (jaccard coefficient, min-hash, etc).  I just did a quick search for "simhash" in GitHub, looks like there are a good 198 repositories that support this (https://github.com/search?q=simhash)!  When I was playing with this I think there were only 50 or so!   There are probably several other approaches that you could take for duplicate detection in text that are in the public domain of utilization, if you plan to commercialize your product.  Good luck with your project and take care!
